backend/controllers/SkkmController.php
<?php

namespace backend\controllers;

use Yii;
use ZipArchive;
use common\models\User;
use common\models\ImportForm;
use common\widgets\QRCodeGenerator;
use yii\base\Security;
use yii\base\Exception;
use yii\data\ArrayDataProvider;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\helpers\Json;
use yii\web\Controller;
use yii\web\UploadedFile;
use yii\web\NotFoundHttpException;
use backend\models\Panitia;
use backend\models\PsUmnEvents;
use backend\models\PsUmnParpntType;
use backend\models\PsUmnPntPerPct;
use backend\models\PsUmnStdntVw;
use backend\models\PsUmnSkkmEntry;
use backend\models\PsUmnStdntAcvty;
use backend\models\SkkmSearch;
use backend\models\SkkmStudentSearch;

/**
 * SkkmController implements the CRUD actions for UMNSkkmEntry model.
 */
class SkkmController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access'=> [
                'class' => AccessControl::className(),
                'only' => ['index', 'view', 'create', 'update', 'delete', 'lists', 'import', 'importview'],//must login to access
                'rules' => [
                    [
                        'actions' => ['index', 'view', 'create', 'update', 'delete', 'lists', 'import', 'importview'],
                        'allow' => true,
                        'roles' => ['@']// hanya dappat diakses oleh user setelah login
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all UMNSkkmEntry models.
     * @return mixed
     *
     * menampilkan halaman yang akan diakses pertama kali saat membuka web
     */
    public function actionIndex()
    {
        $searchModel = new SkkmSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single UMNSkkmEntry model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $skkm = $this->findModel($id);
        $panitia = Panitia::find()->where(['SEQNUM_DAY1' => $skkm->SEQNUM_DAY1])->one();
        if ($panitia) {
        $user = User::find()->where(['id' => $panitia->UserID])->one();
        $PKey = $panitia->PKey;
        $username = $user->username;
        }
        else{        
            $PKey=0;
            $username='Admin';    
        }

        // tabel student actifity
        $searchModel = new SkkmStudentSearch();
        $searchModel->SEQNUM_DAY1=$skkm->SEQNUM_DAY1;
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        if(Yii::$app->request->post('hasEditable'))
        {
            $studentEdit = $_POST['PsUmnStdntAcvty'];
            $row = $_POST['editableIndex'];

            $rowDetail= Yii::$app->request->post('editableKey');
            $find = array(":","{","}",",","\"");
            $rowDetail=str_replace($find, ' ', $rowDetail);

            $editableKey[] = array_filter(explode(' ', $rowDetail));
            $edit[$editableKey[0][2]]=$editableKey[0][4];//SEQNUM_DAY1
            $edit[$editableKey[0][6]]=$editableKey[0][9];//EMPLID
            $edit['UMN_PARTICIPANT_ID'] = $studentEdit[$row]['UMN_PARTICIPANT_ID'];
            $edit['PARTICIPANT_TYPE'] = PsUmnParpntType::findOne(['UMN_PARTICIPANT_ID' => $edit['UMN_PARTICIPANT_ID']])->DESCR;
            
            $StdntAcvty = $this->findModel($edit['SEQNUM_DAY1'],$edit['EMPLID']);

            $out =Json::encode(['output'=>'','message'=>'']);
            $post = [];
            $posted = current($_POST['PsUmnStdntAcvty']);
            $post['PsUmnStdntAcvty'] = $posted;

            $Point = PsUmnPntPerPct::find()
            ->where(['UMN_AREA_ID' => $StdntAcvty->UMN_AREA_ID,'UMN_EVENT_ID' => $StdntAcvty->UMN_EVENT_ID, 'UMN_LEVEL_ID' => $StdntAcvty->UMN_LEVEL_ID, 'UMN_PARTICIPANT_ID' => $edit->UMN_PARTICIPANT_ID])
            ->one();
            if ($Point== null) {
                Yii::$app->session->setFlash('error','Point SKKM untuk event dan type participant tersebut tidak ditemukan. ');
                $ddata=$EMPLID;
                $output = 'Point SKKM tidak ditemukan. ';
                $message = $edit['PARTICIPANT_TYPE'];
                $out = Json::encode(['output'=> $message,'message'=>$output]);
            }        
            else if($StdntAcvty->load($post))
            {
                // save data partisipant yang di update
                $StdntAcvty->save();
                $output = 'NIM : ' . $edit['EMPLID'] . ' - PARTICIPANT ID : ' . $edit['UMN_PARTICIPANT_ID'];
                $message = $edit['PARTICIPANT_TYPE'];
                $out = Json::encode(['output'=> $message,'message'=>'']);
            }
            echo $out;
            return;
        }

        return $this->render('view', 
            [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'model' => $this->findModel($id),
            'PKey' => $PKey,
            'username' => $username,
            ]
        );
    }


    /**
     * Creates a new UMNSkkmEntry model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($id)
    {
        $model = $this->findModel($id);
        $panitia = new Panitia();
        $panitia->SEQNUM_DAY1 = $model->SEQNUM_DAY1;
        $panitia->PKey = Yii::$app->security->generateRandomString(6);
        $username = $model->INSTITUTION . date("Y") . "-" . $model->SEQNUM_DAY1;
        $panitia->signup($username);
        $panitia->save();
        return $this->redirect(['view', 'id' => $model->SEQNUM_DAY1]);
    }

    /**
     * Updates an existing UMNSkkmEntry model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     *
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->SEQNUM_DAY1]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing UMNSkkmEntry model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     *
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

     */

    /**
     * Finds the UMNSkkmEntry model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return UMNSkkmEntry the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = PsUmnSkkmEntry::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    /**
     * mengambil data list events berdasarkan area
     */
    public function actionLists($id)
    {
        $rows = PsUmnEvents::find()->where(['UMN_AREA_ID' => $id])->all();
 
        echo "<option>Select Event</option>";
 
        if(count($rows)>0){
            foreach($rows as $row){
                echo "<option value='$row->UMN_EVENT_ID'>$row->DESCR</option>";
            }
        }
        else{
            echo "<option>There is no event</option>";
        }
 
    }
    /**
     * menampilkan halaman Import excel untuk membuat QR Code
     */
    public function actionImport($id)
    {
        $userid = $id;
        $SKKM = PsUmnSkkmEntry::find()
            ->where('SEQNUM_DAY1 = :id', [':id' => $id])
            ->one();
        $Panitia = Panitia::find()
            ->where('SEQNUM_DAY1 = :userid', [':userid' => $id])
            ->one();
        Yii::$app->session->set('PKey', $Panitia->PKey);

        $model = new ImportForm();
        if ($model->load(Yii::$app->request->post())) {
            $model->excelFile = UploadedFile::getInstance($model, 'excelFile');
            if ($model->upload()) {
            return $this->redirect(['importview', 
                'event'  => $id,
                'excelFile' => $model->excelFile->name,
                'errorCorrectionLevel' => 'L', 
                'matrixPointSize'=> 7
                ]);
            }
        }
        return $this->render('Import', [
                'model' => $model,
                'event' => $SKKM,
            ]);
    }

    /**
     * menampilkan halaman hasil create QR Code dari Import excel
     */
    public function actionImportview($event,$excelFile,$errorCorrectionLevel,$matrixPointSize)
    {
        $PKey = Yii::$app->session->get('PKey');
        $inputFile = 'uploads/' . $excelFile;
        try {
            $inputFileType = \PHPExcel_IOFactory::identify($inputFile);
            $objReader = \PHPExcel_IOFactory::createReader($inputFileType);
            $objPHPExcel = $objReader->load($inputFile);
        } catch (Exception $e) {
            die('Error');
        }
        $sheet = $objPHPExcel->getSheet(0);
        $highestRow = $sheet->getHighestRow();
        $highestColumn = $sheet->getHighestColumn();

        for ($row=1; $row <= $highestRow; $row++) { 
            $rowData = $sheet->rangeToArray('A'.$row.':'.$highestColumn.$row,null,true,false);
            if($row==1 || $rowData[0][0] == '')
            {
                continue;
            }

backend/views/skkm/Import.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\CreateForm */

use yii\helpers\Html;
use yii\helpers\Url;
use yii\bootstrap\ActiveForm;
    use kartik\grid\GridView;
// use common\widgets\QRCodeGenerator;
// use yii\widgets\HelloWidget;

$this->title = 'Create QR Code';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-create">
    <h1><?= Html::encode($this->title) . " '" . $event->DESCR_80  . "' ";?> </h1>

    <p>Please fill out the following fields:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'Import-form']); ?>

                <?= $form->field($model, 'excelFile')->fileInput() ?>

                <!-- <= $form->field($model, 'errorCorrectionLevel') 
                    ->dropDownList(
                        ['L' => 'L - smallest',
                            'M' => 'M',
                            'Q' => 'Q',
                            'H' => 'H - best']
                    );
                    ?>

                <= $form->field($model, 'matrixPointSize')->textInput(['type' => 'number'])?> -->

                <div class="form-group">
                    <?= Html::submitButton('Import', ['class' => 'btn btn-primary', 'name' => 'import-button']) ?>
                </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
     <?php if (Yii::$app->session->hasFlash('Error')): ?>
  <div class="alert alert-danger alert-dismissable">
  <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
  <!-- <h4><i class="icon fa fa-check"></i>Saved!</h4> -->
  <strong>Warning!</strong>  <?= Yii::$app->session->getFlash('Error') ?>
  </div>
<?php endif; ?>
</div>

backend/views/skkm/ImportTable.php
<?php

use yii\helpers\Html;
// use yii\widgets\DetailView;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $model backend\models\UMNSkkmEntry */
// $this->title = $model->SEQNUM_DAY1;
$this->title = 'Create QR Code';
$this->params['breadcrumbs'][] = $this->title;
Yii::$app->params['event']=$event->SEQNUM_DAY1;
?>
<div class="site-create">
    <h1><?= Html::encode($this->title) . " " . $event->DESCR_80 ;?> </h1>
        <?= Html::a('Download QR Code', ['download', 'id' => $event->SEQNUM_DAY1], ['class' => 'btn btn-primary']) ?>
    <?=
    // $this->context->ImportExcel();
                GridView::widget([
                'dataProvider' => $dataProvider,
                'columns' => [
            [
                'attribute' => 'nim',
                'label' => 'NIM Mahasiswa',
            ],
                    [
                        'attribute' => 'nim',
                        'format' => 'html',
                        'label' => 'QR Code',
                        'value' => function ($data) {
                            return Html::img('@web/assets/QR/temp/' . Yii::$app->params['event'] . '/' . $data['nim'].'.png' , ['class' => 'img-responsive center','width' => '60px']);
                        },
                    ],
                ],
            ]);
    // foreach ($dataProvider as $key) {
    //     echo $key."<br>";
    // }
    // print_r($dataProvider);
            ?>

     <?php if (Yii::$app->session->hasFlash('Error')): ?>
  <div class="alert alert-danger alert-dismissable">
  <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
  <!-- <h4><i class="icon fa fa-check"></i>Saved!</h4> -->
  <strong>Warning!</strong>  <?= Yii::$app->session->getFlash('Error') ?>
  </div>
<?php endif; ?>
</div>

backend/views/skkm/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
        use yii\helpers\Url;
use backend\models\PsUmnAreas;
use backend\models\PsUmnEvents;
use backend\models\PsUmnLevels;
use yii\jui\DatePicker;

/* @var $this yii\web\View */
/* @var $model backend\models\UMNSkkmEntry */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="umnskkm-entry-form">

    <?php $form = ActiveForm::begin(); 

        $UMNArea = ArrayHelper::map(PsUmnAreas::find()->all(), 'UMN_AREA_ID', 'DESCR');
        echo $form->field($model, 'UMN_AREA_ID')->dropDownList(
                $UMNArea,
                [
                    'prompt'=>'Select Area',
                    'onchange'=>'
                        $.get( "'.Url::toRoute('/skkm/lists').'", { id: $(this).val() } )
                            .done(function( data ) {
                                $( "#'.Html::getInputId($model, 'UMN_EVENT_ID').'" ).html( data );
                            }
                        );
                    '    
                ]
        ); 

     echo $form->field($model, 'UMN_EVENT_ID')->dropDownList(['prompt'=>'Select Event']);

        ?>

    <?= $form->field($model, 'UMN_LEVEL_ID')->dropDownList(
            ArrayHelper::map(PsUmnLevels::find()->all(),'UMN_LEVEL_ID','DESCR'),
            ['prompt'=>'Select Level']
    ) ?>

    <?= $form->field($model, 'DESCR_80')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'DESCR50_1')->textInput([
                                'maxlength' => true,
                                'value'  => 'Universitas Multimedia Nusantara'
                            ]) ?>

    <?= $form->field($model, 'START_DATE')->widget(\yii\jui\DatePicker::classname(), [
    //'language' => 'ru',
    'dateFormat' => 'yyyy-MM-dd',
    'clientOptions' => ['defaultDate' => date('Y-m-d')],
    ]) ?>

    <?= $form->field($model, 'END_DATE')->widget(\yii\jui\DatePicker::classname(), [
    //'language' => 'ru',
    'dateFormat' => 'yyyy-MM-dd',
    // 'value'  => date('Y-m-d'),
    'clientOptions' => ['defaultDate' => date('Y-m-d')],
    ]) ?>

    <?= $form->field($model, 'COUNT_TOTAL')->textInput([
                                 'type' => 'number',
                                 'value'  => '1'
                            ]) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/skkm/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\SkkmSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="umnskkm-entry-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'INSTITUTION') ?>

    <?= $form->field($model, 'UMN_AREA_ID') ?>

    <?= $form->field($model, 'UMN_EVENT_ID') ?>

    <?= $form->field($model, 'DESCR_80') ?>

    <?= $form->field($model, 'DESCR50_1') ?>

    <?php // echo $form->field($model, 'START_DATE') ?>

    <?php // echo $form->field($model, 'END_DATE') ?>

    <?php // echo $form->field($model, 'UMN_LEVEL_ID') ?>

    <?php // echo $form->field($model, 'COUNT_TOTAL') ?>

    <?php // echo $form->field($model, 'SEQNUM_DAY1') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/skkm/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model backend\models\PsUmnSkkmEntry */

$this->title = 'Create Ps Umn Skkm Entry';
$this->params['breadcrumbs'][] = ['label' => 'Ps Umn Skkm Entries', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="ps-umn-skkm-entry-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/skkm/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\SkkmSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'SKKM';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="umnskkm-entry-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
    </p>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            // 'INSTITUTION',
            'DESCR_80',
            // 'DESCR50_1',
            [
                'attribute' => 'UMN_AREA_ID',
                'value' => 'uMNAREA.DESCR',
            ],
            [
                'attribute' => 'UMN_EVENT_ID',
                'value' => 'uMNEVENT.DESCR',
            ],
            [
                'attribute' => 'UMN_LEVEL_ID',
                'value' => 'uMNLEVEL.DESCR',
            ],
            // 'uMNAREA.DESCR',
            // 'uMNEVENT.DESCR',
            // 'uMNLEVEL.DESCR',
            'START_DATE',
            'END_DATE',
            // 'COUNT_TOTAL',
            // 'SEQNUM_DAY1',

            // ['class' => 'yii\grid\ActionColumn'],
            ['class' => 'yii\grid\ActionColumn', 'template' => '{view}'],
        ],
    ]); ?>
     <?php if (Yii::$app->session->hasFlash('Error')): ?>
  <div class="alert alert-danger alert-dismissable">
  <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
  <!-- <h4><i class="icon fa fa-check"></i>Saved!</h4> -->
  <strong>Warning!</strong>  <?= Yii::$app->session->getFlash('Error') ?>
  </div>
<?php endif; ?>
</div>

backend/views/skkm/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model backend\models\PsUmnSkkmEntry */

$this->title = 'Update Ps Umn Skkm Entry: ' . $model->SEQNUM_DAY1;
$this->params['breadcrumbs'][] = ['label' => 'Ps Umn Skkm Entries', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->SEQNUM_DAY1, 'url' => ['view', 'id' => $model->SEQNUM_DAY1]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="ps-umn-skkm-entry-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/skkm/view.php
<?php

use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use yii\widgets\DetailView;
use kartik\icons\Icon;
use kartik\grid\GridView;
use kartik\editable\Editable;
use kartik\widgets\Select2;
use backend\models\PsUmnParpntType;
use backend\models\PsUmnPntPerPct;
use backend\models\PsUmnSkkmEntry;
// Initialize a specific framework - e.g. Web Hosting Hub Glyphs 
                            Icon::map($this, Icon::BSG);
/* @var $this yii\web\View */
/* @var $model backend\models\UMNSkkmEntry */
$this->title = $model->DESCR_80;
$this->params['breadcrumbs'][] = ['label' => 'SKKM', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="umnskkm-entry-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?php if($PKey!='0'){?>
            <?= Html::a('Create QR Code', ['/site/create', 'id' => $model->SEQNUM_DAY1], ['class' => 'btn btn-primary']) ?>
            <?= Html::a('Import Excel peserta', ['/site/import', 'id' => $model->SEQNUM_DAY1], ['class' => 'btn btn-success']) ?>
            <!-- ?= Html::a('Update My UMN', ['', 'id' => $model->SEQNUM_DAY1], ['class' => 'btn btn-warning']) ?> -->
        <?php 
        }
        else {?>
            <?= Html::a('Create Username & Password', ['create', 'id' => $model->SEQNUM_DAY1], ['class' => 'btn btn-primary']) ?>
        <?php 
        }
        ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            // 'INSTITUTION',
            'SEQNUM_DAY1',
            'DESCR_80',
            'DESCR50_1',
            'uMNAREA.DESCR',
            'uMNEVENT.DESCR',
            'uMNLEVEL.DESCR',
            'START_DATE',
            'END_DATE',
            'COUNT_TOTAL',
            [
            'label' => 'Username',
            'value' => $username,
            ],
            'panitia.PKey',
        ],
    ]) ?>

     <?php if (Yii::$app->session->hasFlash('Error')): ?>
  <div class="alert alert-danger alert-dismissable">
  <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
  <!-- <h4><i class="icon fa fa-check"></i>Saved!</h4> -->
  <strong>Warning!</strong>  <?= Yii::$app->session->getFlash('Error') ?>
  </div>
<?php endif; ?>


    <!-- <h1>?= Html::encode($this->title) ?></h1> -->
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <!-- <p>
        ?= Html::a('Create UMN Student SKKM', ['create'], ['class' => 'btn btn-success']) ?>
    </p> -->
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            // 'INSTITUTION',
            'EMPLID',
            [
                'attribute' => 'Nama',
                'label' => 'Nama Mahasiswa',
                'value' => 'mahasiswa.NM',
            ],
            // 'uMNAREA.DESCR',
            // 'uMNEVENT.DESCR',
            // 'uMNLEVEL.DESCR',
            // 'uMNSkkmEntry.DESCR_80',
            // 'uMNPARTICIPANT.DESCR',
            // 'UMN_OBTAIN_POINTS',
            // 'ATTEND_PRESENT',
            // 'uMNEVENT.POINTS',
            // [
            //     // 'label' => 'Events',
            //     'attribute' => 'SEQNUM_DAY1',
            //     'value' => 'uMNSkkmEntry.DESCR_80',
            // ],
            [
                'attribute' => 'UMN_PARTICIPANT_ID',
                // 'filter' => ArrayHelper::map(PsUmnParpntType::find()->orderBy(['DESCR'=>SORT_ASC])->all(),'UMN_PARTICIPANT_ID','DESCR'),
                'value' => 'uMNPARTICIPANT.DESCR',
                        //menggunakan widget untuk editable column
                        'class' => 'kartik\grid\EditableColumn',
                        //list data dropdown dari DB
                        'editableOptions' => [
                            'header' => 'tipe partisipan',
                            'asPopover' => false,
                            'format' => Editable::FORMAT_BUTTON,
                            'inputType' => Editable::INPUT_DROPDOWN_LIST,
                            'inputType' => '\kartik\select2\Select2',
                            'options'=>
                            [
                                'data' => ArrayHelper::map(PsUmnParpntType::find()->all(),'UMN_PARTICIPANT_ID', 'DESCR'),
                            ],
                        ],
            ],
            [
                'label' => 'Points',
                'attribute' => 'Points',
                // 'filterInputOptions' => 'number',
                // 'filterOptions' => [ 'type' => 'number'],
                'filterInputOptions' => [
                    'class' => 'form-control',
                    'type' => 'number'
                ],
                'value' => function($data){
                    if ($text = PsUmnPntPerPct::findOne(['UMN_AREA_ID' => $data['UMN_AREA_ID'],'UMN_EVENT_ID' => $data['UMN_EVENT_ID'],'UMN_LEVEL_ID' => $data['UMN_LEVEL_ID'],'UMN_PARTICIPANT_ID' => $data['UMN_PARTICIPANT_ID']])->POINTS) {
                        return $text;
                    }
                    else return 0;
                        },   
            ],
            [
                'attribute' => 'COUNT_TOTAL',
                'filterInputOptions' => [
                    'class' => 'form-control',
                    'type' => 'number'
                ],
            ],
            [
                'label' => 'Status',
                'attribute' => 'ATTEND_PRESENT',
                'format' => 'html',
                'filter' => [ 'Y' => 'Yes', 'N' => 'No'],
                'value' => function($data){
                            if ($data['ATTEND_PRESENT'] == 'Y') {
                                return Icon::show('ok', ['aria-hidden'=>"true",'style'=>"color:green;text-shadow:2px 2px 4px #000000;"], Icon::BSG);
                            } else {
                                return Icon::show('remove', ['aria-hidden'=>"true",'style'=>"color:red;text-shadow:2px 2px 4px #000000;"], Icon::BSG);
                            }
                        },   
                
            ],
            [
                'label' => 'On The Spot',
                'attribute' => 'CREATE_DATE',
                'format' => 'html',
                // 'filter' => [ 'Y' => 'Yes', 'N' => 'No'],
                'value' => function($data){
                    // $expression = new Expression('NOW()');
                    // $now = (new \yii\db\Query)->select($expression)->scalar();  // SELECT NOW();
                    $Event=PsUmnSkkmEntry::find()->where(['SEQNUM_DAY1' => $data['SEQNUM_DAY1']])->one();
                            if ($data['CREATE_DATE'] <= $Event->START_DATE) {
                                return Icon::show('remove', ['aria-hidden'=>"true",'style'=>"color:red;text-shadow:2px 2px 4px #000000;"], Icon::BSG);
                            } else {
                                return Icon::show('ok', ['aria-hidden'=>"true",'style'=>"color:green;text-shadow:2px 2px 4px #000000;"], Icon::BSG);
                            }
                        },   
                
            ],
            // 'ATTEND_PRESENT',
            [   
                'class' => 'yii\grid\ActionColumn', 
                'template' => '{view} {update}',
                'controller' => 'skkm-student'     
            ],
        ],
    ]); ?>

</div>